build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
    run_test:
        image: python:2-alpine
        commands:
            - pip install -r requirements.txt
            - python testing.py
publish:
    docker:
        repo: $$DOCKER_USERNAME/cicd
        tag: latest
        username: lawchung
        password: chung1
        email: lawchung@cisco.com
deploy:
    webhook:
       image: plugins/drone-webhook
       skip_verify: true
       method: POST
       auth:
           username: CICD1
           password: CICD1
       urls:
          - https://$$MANTL_CONTROL/marathon/v2/apps/class/$$DOCKER_USERNAME/restart?force=true
notify:
    spark:
       image: hpreston/drone-spark
       auth_token: Njk4ZDgzODctZGFmNS00OTJmLTgxMjQtYmQ4M2Q3OWJiZWFmZDMxYzM2ZDItZThm
       roomID: Y2lzY29zcGFyazovL3VzL1RFQU0vOTk0ZDExMTAtMWU2ZS0xMWU3LWFhYTUtNTliNzk1OTc2MGIx
